apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-open-movie-database
  name: react-open-movie-database
spec:
  ports:
  - name: react-open-movie-database
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: react-open-movie-database
  type: LoadBalancer
